language: node_js

node_js:
  - "8.11.3"
dist: trusty
sudo: required
addons:
  chrome: stable
  hostname: localhost
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
    - node_modules

install: 
  - npm cache clean --force
  - npm install
  - npm install pm2 -g

before_script: 
  - pm2 start npm -- run dev
  
script:
  - pm2 list
  - npm test home 
