language: node_js

node_js:
  - "8.11.3"
dist: trusty
sudo: required
addons:
  apt:
    packages:
      # This is required to run new chrome on old trusty, taken from:
      # https://github.com/GoogleChrome/puppeteer/blob/v1.8.0/.travis.yml#L7
      - libnss3 
  chrome: stable
  hostname: localhost
  
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000 &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  
before_script:
  - pm2 start npm -- run dev
  
cache:
  directories:
    - node_modules

install: 
  - npm cache clean --force
  - npm install
  - npm install pm2 -g

script:
  - npm test home
